#!/usr/bin/env python3
"""Validate a book skill generated by weread-to-skill."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


REQUIRED_FILES = (
    "SKILL.md",
    "agents/openai.yaml",
    "references/concepts.md",
    "references/source-map.md",
    "references/reader-notes.md",
    "state/sync.json",
)


def validate(root: Path) -> list[str]:
    errors: list[str] = []
    for relative in REQUIRED_FILES:
        if not (root / relative).is_file():
            errors.append(f"Missing {relative}")
    if errors:
        return errors

    skill_text = (root / "SKILL.md").read_text(encoding="utf-8")
    match = re.match(r"^---\n(.*?)\n---\n", skill_text, re.DOTALL)
    if not match:
        errors.append("SKILL.md frontmatter is missing or malformed")
    else:
        frontmatter = match.group(1)
        keys = [line.split(":", 1)[0].strip() for line in frontmatter.splitlines() if ":" in line]
        if keys != ["name", "description"]:
            errors.append("SKILL.md frontmatter must contain only name and description")
        name_match = re.search(r"^name:\s*(\S+)\s*$", frontmatter, re.MULTILINE)
        if not name_match or not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name_match.group(1)):
            errors.append("Skill name is not valid kebab-case")
    if "not full-book coverage" not in skill_text:
        errors.append("SKILL.md lacks the full-book coverage disclosure")

    try:
        state = json.loads((root / "state/sync.json").read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        errors.append(f"Invalid state/sync.json: {exc}")
        return errors
    source_ids = state.get("source_ids")
    concept_ids = state.get("concept_ids")
    if not isinstance(source_ids, list) or not source_ids:
        errors.append("state.source_ids must be a non-empty array")
    if not isinstance(concept_ids, list) or not concept_ids:
        errors.append("state.concept_ids must be a non-empty array")

    concepts_text = (root / "references/concepts.md").read_text(encoding="utf-8")
    for concept_id in concept_ids or []:
        if f"`{concept_id}`" not in concepts_text:
            errors.append(f"Concept {concept_id!r} is absent from concepts.md")
    known_sources = set(source_ids or [])
    cited_sources = set(re.findall(r"`([hrp]:[^`]+)`", concepts_text))
    unknown = sorted(cited_sources - known_sources)
    if unknown:
        errors.append(f"Concepts cite unknown sources: {unknown}")
    if not cited_sources:
        errors.append("No source IDs are cited in concepts.md")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("skill_dir", type=Path)
    args = parser.parse_args()
    errors = validate(args.skill_dir)
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print(f"Valid generated skill: {args.skill_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
